export const FEATURE_LABELS = {
  trend:{title:"Price trend",positive:"Price has been climbing over the recent window.",negative:"Price has been falling over the recent window."},
  momentum:{title:"Short-term momentum",positive:"The latest real bars are accelerating upward.",negative:"The latest real bars are accelerating downward."},
  volume:{title:"Volume",positive:"The latest real bar has more volume than its recent average.",negative:"The latest real bar has lighter volume than its recent average."},
  volatility:{title:"Volatility",positive:"Price is moving around more than its recent baseline.",negative:"Price movement is relatively calm."},
  orderFlow:{title:"Bar pressure",positive:"The latest real bar closed toward its high.",negative:"The latest real bar closed toward its low."},
  breadth:{title:"Monitored-symbol breadth",positive:"More of the monitored symbols are rising together.",negative:"More of the monitored symbols are weakening together."},
  vwap:{title:"Price vs. VWAP",positive:"Price is above its recent real volume-weighted average.",negative:"Price is below its recent real volume-weighted average."}
,
  ret1:{title:"1-minute return",positive:"The latest minute moved up.",negative:"The latest minute moved down."},
  ret3:{title:"3-minute momentum",positive:"The recent 3-minute move is positive.",negative:"The recent 3-minute move is negative."},
  ret5:{title:"5-minute momentum",positive:"Price has been strengthening over five minutes.",negative:"Price has been weakening over five minutes."},
  ret10:{title:"10-minute trend",positive:"The 10-minute move is positive.",negative:"The 10-minute move is negative."},
  ret20:{title:"20-minute trend",positive:"The broader short-term trend is positive.",negative:"The broader short-term trend is negative."},
  momAccel:{title:"Momentum acceleration",positive:"Momentum is accelerating upward.",negative:"Momentum is accelerating downward."},
  body:{title:"Candle pressure",positive:"The current bar closed strongly versus its open.",negative:"The current bar closed weakly versus its open."},
  range:{title:"Current range",positive:"The latest bar is unusually wide.",negative:"The latest bar is relatively narrow."},
  upperWick:{title:"Upper rejection",positive:"Price recently rejected from the upper part of the bar.",negative:"Upper rejection is limited."},
  lowerWick:{title:"Lower rejection",positive:"Price recently rejected from the lower part of the bar.",negative:"Lower rejection is limited."},
  rv5:{title:"5-minute volatility",positive:"Very recent price movement is elevated.",negative:"Very recent movement is calm."},
  rv20:{title:"20-minute volatility",positive:"Short-term volatility is elevated.",negative:"Short-term volatility is subdued."},
  volRel5:{title:"5-minute relative volume",positive:"Current activity is above its recent 5-minute norm.",negative:"Current activity is below its recent 5-minute norm."},
  volRel20:{title:"20-minute relative volume",positive:"Current activity is above its 20-minute norm.",negative:"Current activity is below its 20-minute norm."},
  volAccel:{title:"Volume acceleration",positive:"Trading activity is accelerating.",negative:"Trading activity is slowing."},
  vwapDist:{title:"Distance from VWAP",positive:"Price is above recent VWAP.",negative:"Price is below recent VWAP."},
  ma5Dist:{title:"Distance from 5-bar average",positive:"Price is above its very short average.",negative:"Price is below its very short average."},
  ma20Dist:{title:"Distance from 20-bar average",positive:"Price is above its short-term average.",negative:"Price is below its short-term average."},
  maCross:{title:"Fast vs. slow average",positive:"The fast average is above the slow average.",negative:"The fast average is below the slow average."},
  high20Dist:{title:"Distance from 20-bar high",positive:"Price is close to a recent high.",negative:"Price is farther below the recent high."},
  low20Dist:{title:"Distance from 20-bar low",positive:"Price is well above a recent low.",negative:"Price is close to a recent low."},
  rangeCompression:{title:"Range compression",positive:"Recent range is expanding versus its baseline.",negative:"Recent range is compressing versus its baseline."},
  trendSlope10:{title:"10-bar slope",positive:"The recent price slope points upward.",negative:"The recent price slope points downward."},
  trendSlope30:{title:"30-bar slope",positive:"The broader intraday slope points upward.",negative:"The broader intraday slope points downward."},
  closeLocation:{title:"Location in recent range",positive:"Price is near the upper part of its recent range.",negative:"Price is near the lower part of its recent range."},
  timeSin:{title:"Time-of-day pattern",positive:"The model sees a time-of-day condition associated with this class.",negative:"The time-of-day condition weighs against this class."},
  timeCos:{title:"Time-of-day cycle",positive:"The session timing supports this model output.",negative:"The session timing weighs against this model output."}
,
  spyRet5:{title:"SPY 5-minute context",positive:"The broad S&P 500 market is strengthening over five minutes.",negative:"The broad S&P 500 market is weakening over five minutes."},
  qqqRet5:{title:"QQQ 5-minute context",positive:"Nasdaq/technology context is strengthening.",negative:"Nasdaq/technology context is weakening."},
  breadth5:{title:"Live breadth context",positive:"More monitored U.S. names are rising than falling.",negative:"More monitored U.S. names are falling than rising."},
  relativeSpy5:{title:"Strength vs. SPY",positive:"This stock is outperforming SPY over the same five-minute window.",negative:"This stock is underperforming SPY over the same five-minute window."},
  relativeQqq5:{title:"Strength vs. QQQ",positive:"This stock is outperforming QQQ over the same five-minute window.",negative:"This stock is underperforming QQQ over the same five-minute window."}
};
